package com.NFCFZLLE.eventmanagement.entities;

/**
 * Created by t-tahir on 11/01/2016.
 */
public enum RequestKeys {

    CHECK_IN_REQUEST_BY_BEACON_ID, ATTENDEE_REGISTER_REQUEST, CHECK_IN_REQUEST_BY_NFC_ID, CHECK_OUT_REQUEST_BY_NFC_ID, APP_DATA_REQUEST, CHECK_OUT_REQUEST_BY_QR_ID, CHECK_IN_REQUEST_BY_QR_ID, UPDATE_LOCATION, FORGOT_PASSWORD_REQUEST, LOGIN_REQUEST



}
